pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                echo "Build number:
                sh "docker image build . -t ecr.com/webserver:${env.BUILD_NUMBER}"
            }
        }
    }
}