pipeline {
    agent any

    parameters {
        string(defaultValue: "", description: "Deployment Name?", name: "deploymentName")
        choice(choices: ["EU-WEST-2A", "WEST-2B", "EU-WEST-2C"], description: "What AZ?", name: "azDeploy")
        booleanParam(defaultValue: false, description: "CONFIRM DEPLOYMENT?", name: "confirmDeploy")
    }

    stages {
        stage("Deploy") {
            steps {
                echo "String is: ${params.deploymentName} \n"
                echo "choice is: ${params.azDeploy} \n"
                script {
                    if(params.booleanParam == false) {
                        currentBuild.result = "SUCCESS"
                    }
                    else{
                        echo "booleanParam is: ${params.confirmDeploy}"
                    }
                }

            }
        }
    }
}