pipeline {
    agent any
    stages {
        stage("Stage1") {
            steps {
                echo "Stage1"
            }
        }
                stage("Stage2") {
            steps {
                echo "Stage2"
            }
        }
                stage("Stage3") {
            steps {
                echo "Stage3"
            }
        }
                stage("Stage4") {
            steps {
                echo "Stage4"
            }
        }
                stage("Stage5") {
            steps {
                echo "Stage5"
            }
        }
    }
}